apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb-system
spec:
  addresses:
    - 192.168.134.200-192.168.134.200 # Sử dụng một IP tự do trong dải NAT để làm IP LoadBalancer truy cập từ Windows Host
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-adv
  namespace: metallb-system
